### PR TITLE
Fixed the issue with numpy 1.24

### LINKED ISSUE #3: incompatible with numpy 1.24.1
It seems that raster-geometry uses numpy.float, which does not exist anymore on numpy 1.24 

I guess it's possible to replace it with numpy.single ( https://numpy.org/doc/stable/user/basics.types.html )

### PR DESCRIPTION
**Pull request by AdnanAvdagic**
Fixes
#3

### CODE REVIEW

**Review by norok2 — CHANGES_REQUESTED** [review]
I would rather use `np.float_` instead of `np.double`. Can you confirm that it would work for you?

**Comment by AdnanAvdagic** [comment]
It does indeed work for us!
When can you ship a new version on pypi?

**Review by norok2 — APPROVED** [review]

**Comment by AdnanAvdagic** [comment]
When can we expect this on pypi? @norok2

**Comment by norok2** [comment]
Hi, unfortunately it is difficult for me to commit to short-term actions. However, I have already managed to ship it to PyPI. Can you confirm that it works as you expect? Thanks

**Pull request merged**
